version: "2.3"
title: "Coffee"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 4
    label: "paper towel sheet"
  - id: 5
    label: "water jug lid"
  - id: 6
    label: "water jug (open)"
  - id: 7
    label: "water jug (closed)"
  - id: 18
    label: "kettle lid"
  - id: 19
    label: "kettle (open)"
  - id: 20
    label: "kettle (closed)"
  - id: 24
    label: "measuring cup"
  - id: 25
    label: "container" # prep bowl
  - id: 26
    label: "mug"
  - id: 27
    label: "kettle switch"
  - id: 28
    label: "thermometer (open)"
  - id: 29
    label: "thermometer (closed)"
  - id: 30
    label: "timer (on)"
  - id: 31
    label: "timer (off)"
  - id: 32
    label: "trash can"
  # Labels unique to coffee
  - id: 33
    label: "coffee + mug"
  - id: 34
    label: "coffee bag"
  - id: 35
    label: "coffee beans + container"
  - id: 36
    label: "coffee beans + container + scale"
  - id: 37
    label: "coffee grounds + paper filter (quarter - open) + dripper"
  - id: 38
    label: "coffee grounds + paper filter (quarter - open) + dripper + mug"
  - id: 39
    label: "container + scale"
  - id: 40
    label: "dripper" # previously filter cone
  - id: 41
    label: "dripper + mug"
  - id: 42
    label: "grinder lid"
  - id: 43
    label: "grinder (open)"
  - id: 44
    label: "grinder (closed)"
  - id: 45
    label: "paper filter"
  - id: 46
    label: "paper filter (semi)"
  - id: 47
    label: "paper filter (quarter)"
  - id: 48
    label: "used paper filter (quarter) + dripper"
  - id: 49
    label: "paper filter (quarter) + dripper"
  - id: 50
    label: "paper filter (quarter) + dripper + mug"
  - id: 51
    label: "paper filter (quarter - open) + dripper"
  - id: 52
    label: "paper filter (quarter - open) + dripper + mug"
  - id: 53
    label: "paper filter bag"
  - id: 54
    label: "stack of paper filters"
  - id: 55
    label: "scale (on)"
  - id: 56
    label: "scale (off)"
  - id: 57
    label: "used paper filter" # out of the mug completely
  - id: 58
    label: "used paper filter (quarter - open) + dripper"
  - id: 59
    label: "used paper filter (quarter - open) + dripper + mug"
  - id: 121
    label: "used paper filter (quarter) + dripper + mug"
