version: "2.2"
title: "Oatmeal"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 4
    label: "paper towel sheet"
  - id: 5
    label: "water jug lid"
  - id: 6
    label: "water jug (open)"
  - id: 7
    label: "water jug (closed)"
  - id: 8
    label: "cutting board"
  - id: 9
    label: "butter knife"
  - id: 10
    label: "banana"
  - id: 11
    label: "banana (peeled)"
  - id: 12
    label: "sliced banana"
  - id: 13
    label: "cinnamon (open)"
  - id: 14
    label: "cinnamon (closed)"
  - id: 21
    label: "spoon"
  - id: 22
    label: "jar of honey (open)"
  - id: 23
    label: "jar of honey (closed)"
  - id: 24
    label: "measuring cup"
  - id: 25
    label: "container" # prep bowl
  # Labels unique to oatmeal
  - id: 72
    label: "tablespoon"
  - id: 73
    label: "tablespoon + oats"
  - id: 74
    label: "bowl"
  - id: 75
    label: "microwave (open)"
  - id: 76
    label: "microwave (closed)"
  - id: 77
    label: "container of oats lid"
  - id: 78
    label: "container of oats (open)"
  - id: 79
    label: "container of oats (closed)"
  - id: 80
    label: "box of raisins"
  - id: 81
    label: "raisins"
  - id: 82
    label: "container + raisins"
  - id: 83
    label: "bowl + oats"
  - id: 84
    label: "bowl + water"
  - id: 85
    label: "bowl + oats + water"
  - id: 86
    label: "bowl + oats + water + raisins"
  - id: 87
    label: "oatmeal" # "bowl + oats + water + raisins (stirred)"
  - id: 88
    label: "oatmeal + sliced banana"
  - id: 89
    label: "oatmeal + cinnamon"
  - id: 90
    label: "oatmeal + honey"
  - id: 91
    label: "oatmeal + sliced banana + cinnamon"
  - id: 92
    label: "oatmeal + sliced banana + honey"
  - id: 93
    label: "oatmeal + sliced banana + cinnamon + honey"
  - id: 122
    label: "oatmeal + cinnamon + honey"
