#_BASE_: "/angel_workspace/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
_BASE_: "/home/local/KHQ/hannah.defazio/angel_system/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
MODEL:
  #WEIGHTS: '/angel_workspace/model_files/berkeley_model_r50_final.pth'
  WEIGHTS: "/data/PTG/cooking/training/object_detector/stage1/berkeley/resnet50_plus_bkgd/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
#    NUM_CLASSES: 1203
    NUM_CLASSES: 42
    SCORE_THRESH_TEST: 0.0001
    NAME: StandardROIHeads_PLUS_CONTACT
INPUT:
  MIN_SIZE_TRAIN: (720,)
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280
DATASETS:
  TRAIN: ("COFFEE_UCB_train",)
  TEST: ("COFFEE_UCB_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300

DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.5
  FILTER_EMPTY_ANNOTATIONS: False

OUTPUT_DIR: '/data/PTG/cooking/training/object_detector/stage1/berkeley/resnet50_plus_bkgd'

SOLVER:
  TOTAL_IMAGE_NUMBER: 1516
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  STEPS: (34000, 41000)
  CHECKPOINT_PERIOD: 1000
  EPOCH: 50

VISUALIZER:
  CAM: False

