#_BASE_: "/angel_workspace/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
_BASE_: "/home/local/KHQ/hannah.defazio/angel_system/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    #NUM_CLASSES: 42 # coffee
    NUM_CLASSES: 49 # coffee + tea
    SCORE_THRESH_TEST: 0.0001
    NAME: StandardROIHeads
    #NAME: StandardROIHeads_PLUS_CONTACT
INPUT:
  MIN_SIZE_TRAIN: (720,)
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280
DATASETS:
  TRAIN: ("COFFEE_TEA_UCB_train",)
  TEST: ("COFFEE_TEA_UCB_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300

DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.5
  FILTER_EMPTY_ANNOTATIONS: True

OUTPUT_DIR: '/data/PTG/cooking/training/object_detector/stage1/coffee+tea/berkeley/resnet50'

SOLVER:
  #TOTAL_IMAGE_NUMBER: 1516 # coffee
  TOTAL_IMAGE_NUMBER: 1991 # coffee + tea
  IMS_PER_BATCH: 12
  BASE_LR: 0.001
  STEPS: (34000, 41000)
  CHECKPOINT_PERIOD: 1000
  EPOCH: 50

VISUALIZER:
  CAM: False
